from pathlib import Path
p=Path(__file__).parent
a=(p/'app.js').read_text('utf8')
def rep(old,new):
 global a
 if old not in a:raise ValueError('missing '+old[:80])
 a=a.replace(old,new,1)
rep("const POWER={GAS:'가솔린',HEV:'하이브리드',EV:'전기차',DIESEL:'디젤',PHEV:'플러그인 하이브리드'};","const POWER={GAS:'가솔린',HEV:'하이브리드',EV:'전기차',DIESEL:'디젤',PHEV:'플러그인 하이브리드',FCEV:'수소전기차',MIXED:'트림별 확인'};\nconst hasPrice=v=>Number.isFinite(v.price)&&v.price>0;\nconst priceText=v=>hasPrice(v)?money(v.price):'가격 확인 필요';\nconst seatsText=v=>v.seats?('최대 '+v.seats+'명'):'인승 검증 필요';\nconst priceSort=v=>hasPrice(v)?v.price:Number.POSITIVE_INFINITY;\nconst hasQuoteBase=(v,cfg)=>Boolean(verifiedGet(v.id))||hasPrice(v)||(Number(cfg?.actualPrice)>0);")
rep("function priceLabel(car){const spec=verifiedGet(car.id);return spec?spec.priceDate+' 공식 확인':car.status==='official'?'시작가 공식 출처':'참고 추정';}","function priceLabel(car){const spec=verifiedGet(car.id);return spec?spec.priceDate+' 일부 트림 검증':!hasPrice(car)?'공식 목록 · 가격 미확정':car.priceProof==='published-start'?'공식 사이트 공개 시작가':car.status==='official'?'기존 시작가 · 재확인 필요':'참고 추정';}")
rep("<span class=\"pill\">최대 ${car.seats}명</span>","<span class=\"pill\">${safe(seatsText(car))}</span>")
rep("const src=pictureMemo.get(v.id)||v.image||'';","const src=pictureMemo.get(v.id)||v.image||'';")
rep("<strong>${money(v.price)}</strong>","<strong>${priceText(v)}</strong>")
rep("if(v&&!v.image&&!pictureMemo.has(id))lookupCommons(v,el);","if(v&&!v.image&&!pictureMemo.has(id)&&!v.id.startsWith('market-'))lookupCommons(v,el);")
rep("&&(!price||v.price<=price));","&&(!price||(hasPrice(v)&&v.price<=price))&&(document.getElementById('verificationFilter').value==='any'||(document.getElementById('verificationFilter').value==='packages'&&verifiedGet(v.id))||(document.getElementById('verificationFilter').value==='priced'&&hasPrice(v))||(document.getElementById('verificationFilter').value==='unpriced'&&!hasPrice(v))));")
rep("if(sort==='priceAsc')cars.sort((a,b)=>a.price-b.price);else if(sort==='priceDesc')cars.sort((a,b)=>b.price-a.price);else if(sort==='name')cars.sort((a,b)=>a.name.localeCompare(b.name,'ko'));else if(resultMode!=='recommend')cars.sort((a,b)=>a.price-b.price);","if(sort==='priceAsc')cars.sort((a,b)=>priceSort(a)-priceSort(b));else if(sort==='priceDesc')cars.sort((a,b)=>(hasPrice(b)?b.price:-1)-(hasPrice(a)?a.price:-1));else if(sort==='name')cars.sort((a,b)=>a.name.localeCompare(b.name,'ko'));else if(resultMode!=='recommend')cars.sort((a,b)=>priceSort(a)-priceSort(b));")
rep("const rows=[['기본 시작가',v=>money(v.price)+' / '+priceLabel(v)]","const rows=[['기본 시작가',v=>priceText(v)+' / '+priceLabel(v)]")
rep("['최대 탑승 인원',v=>v.seats+'명']","['최대 탑승 인원',v=>seatsText(v)]")
rep("['시뮬레이션 총액',v=>money(makeCalc(v,saved[v.id]||{}).total)+(verifiedGet(v.id)?' · 추정 세금 포함':' · 옵션 미확정')]","['시뮬레이션 총액',v=>hasQuoteBase(v,saved[v.id])?money(makeCalc(v,saved[v.id]||{}).total)+(verifiedGet(v.id)?' · 추정 세금 포함':' · 옵션 미확정'):'가격 미확정 · 계산 보류']")
rep("'선택 트림가: '+money(x.base)","'선택 트림가: '+(hasQuoteBase(v,working)?money(x.base):'미확정')")
rep("'차량 출고가 기준: '+money(x.vehiclePrice)","'차량 출고가 기준: '+(hasQuoteBase(v,working)?money(x.vehiclePrice):'미확정')")
rep("'비교용 총구매 예상: '+money(x.total),'월 할부 예시: '+money(x.monthly)","'비교용 총구매 예상: '+(hasQuoteBase(v,working)?money(x.total):'미확정'),'월 할부 예시: '+(hasQuoteBase(v,working)?money(x.monthly):'미확정')")
rep("actualPrice:from.actualPrice||car.price","actualPrice:from.actualPrice||car.price||0")
rep("· 최대 ${v.seats}명</p>","· ${safe(seatsText(v))}</p>")
rep("<strong>${money(v.price)} · ${safe(priceLabel(v))}</strong>","<strong>${priceText(v)} · ${safe(priceLabel(v))}</strong>")
rep("<strong>${safe(SIZES[v.size])} · 최대 ${v.seats}명</strong>","<strong>${safe(SIZES[v.size])} · ${safe(seatsText(v))}</strong>")
rep("value=\"${audit?selectedTrim.price:cfg.actualPrice}\"","value=\"${audit?selectedTrim.price:(cfg.actualPrice||'')}\" placeholder=\"공식 견적 확인 후 입력\"")
rep("const x=makeCalc(v,cfg),list=chosen.map", "const x=makeCalc(v,cfg),list=chosen.map")
rep("const statusText=!audit?", "const statusText=!audit?")
rep("$('calcSummary').innerHTML=`<span style=", "if(!hasQuoteBase(v,cfg)){$('calcSummary').innerHTML='<strong class=\"unknown-price\">총구매예산 계산 보류</strong><p>이 모델은 공식 가격 및 세부 옵션이 아직 검증되지 않았습니다. 제조사 가격표를 확인하여 위의 차량 기준 가격에 실제 금액을 입력하면 예산 시뮬레이션을 사용할 수 있습니다. 임의로 0원 처리하지 않습니다.</p>';return;}\n $('calcSummary').innerHTML=`<span style=")
rep("for(const id of ['search','brandFilter','originFilter','bodyFilter','powerFilter','sizeFilter','priceFilter','sortSelect'])", "for(const id of ['search','brandFilter','originFilter','bodyFilter','powerFilter','sizeFilter','priceFilter','verificationFilter','sortSelect'])")
rep("$('moreBtn').addEventListener('click',()=>{shown+=12;renderBrowse()});","$('moreBtn').addEventListener('click',()=>{shown+=12;renderBrowse()});\n $('catalogExport').addEventListener('click',()=>{const cols=['brand','name','origin','body','power','seats','price','priceProof','catalogState','official'];const csv=[cols.join(','),...VEHICLES.map(v=>cols.map(k=>'\"'+String(v[k]??'').replace(/\"/g,'\"\"')+'\"').join(','))].join('\\n');download('AutoPicker_국내차량목록_20261008.csv','\\ufeff'+csv,'text/csv;charset=utf-8');notify('차량 목록 CSV를 저장했습니다.');});")
rep("box.innerHTML=labels.map(t=>`<span>${safe(t)}</span>`).join('')+", "box.innerHTML=labels.map(t=>`<span>${safe(t)}</span>`).join('')+")
# comparison desired feature still no 0 price claim: no-price guarded
# UI stats with separate coverage
rep("updateCounts(){const count=Object.keys(saved).length;$('favCounter').textContent=count;$('totalCars').textContent=VEHICLES.length;$('totalBrands').textContent=new Set(VEHICLES.map(c=>c.brand)).size;}","updateCounts(){const count=Object.keys(saved).length;$('favCounter').textContent=count;$('totalCars').textContent=VEHICLES.length;$('totalBrands').textContent=new Set(VEHICLES.map(c=>c.brand)).size;const verifiedEl=$('verifiedCount');if(verifiedEl)verifiedEl.textContent=Object.keys(AutoVerified.catalog).length;}")
(p/'app.js').write_text(a,'utf8')
html=(p/'index.html').read_text('utf8')
html=html.replace('v2.6.0','v2.7.0')
html=html.replace('<div><strong>3단계</strong><span>추천 · 비교 · 견적</span></div>', '<div><strong id="verifiedCount">—</strong><span>공식 옵션 일부 검증 모델</span></div>')
html=html.replace('<div class="notice"><strong>구매 전 꼭 확인하세요.</strong>', '<div class="notice"><strong>일괄 카탈로그 안내.</strong> 현재 국내 공식 브랜드의 모델 목록을 확대한 탐색용 자료입니다. 전체 시판 차량·특정 트림의 주문 가능 여부를 100% 보증하지 않으며, 공식 모델 목록에 나와도 실제 판매·재고 상황은 다를 수 있습니다. <b>가격과 좌석 정보가 미확인된 모델은 추정 견적을 만들지 않습니다.</b></div><div class="notice"><strong>구매 전 꼭 확인하세요.</strong>')
html=html.replace('<option>MPV</option></select>', '<option>MPV</option><option>픽업</option><option>쿠페</option><option>해치백</option><option>왜건</option><option>컨버터블</option><option>상용</option></select>')
html=html.replace('<option value="EV">전기차</option></select>', '<option value="EV">전기차</option><option value="PHEV">플러그인 하이브리드</option><option value="DIESEL">디젤</option><option value="FCEV">수소전기차</option></select>')
html=html.replace('<label>기본가 상한<select id="priceFilter">', '<label>데이터 검증<select id="verificationFilter"><option value="any">전체 상태</option><option value="packages">공식 트림·옵션 일부 검증</option><option value="priced">가격 등록</option><option value="unpriced">가격 미확인</option></select></label><label>기본가 상한<select id="priceFilter">')
html=html.replace('<div class="result-toolbar"><span id="resultCount">', '<div class="catalog-tools"><span>공식 목록 기반 · 2026.10.08 스냅샷 · 최종 판매 여부 별도 확인</span><button id="catalogExport" class="secondary" type="button">전체 모델·출처 CSV ↓</button></div><div class="result-toolbar"><span id="resultCount">')
html=html.replace('제조사 최종 확인</span>', '제조사 최종 확인 · 목록 등록과 가격 검증은 별개</span>')
(p/'index.html').write_text(html,'utf8')
css=(p/'styles.css').read_text('utf8')+"\n/* v2.7.0 market-catalog */\n.catalog-tools{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;padding:10px 0;color:#9bafcc;font-size:12px}.catalog-tools .secondary{min-height:36px}.unknown-price{font-size:19px;color:#fbbf83}.source-badge{max-width:100%;overflow-wrap:anywhere}@media(max-width:600px){.catalog-tools{align-items:flex-start;flex-direction:column}.catalog-tools button{width:100%}}\n"
(p/'styles.css').write_text(css,'utf8')
