'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');
const core=require('./core'),verified=require('./catalog-verified');
const cx={AutoCore:core,AutoVerified:verified,console};vm.createContext(cx);
vm.runInContext(fs.readFileSync('./data.js','utf8')+'\nglobalThis.testVehicles=VEHICLES;',cx);
vm.runInContext(fs.readFileSync('./feature-fit.js','utf8'),cx);
const vehicles=cx.testVehicles,fit=cx.AutoFeatureFit,car=id=>vehicles.find(c=>c.id===id);
let n=0;const check=(label,fn)=>{fn();console.log('PASS '+(++n)+' '+label);};
check('321 model families indexed',()=>assert.equal(vehicles.length,321));
check('verified catalog subset',()=>assert.deepEqual(Object.keys(verified.catalog),['seltos','carnival','santafe-hev','palisade','sportage','sportage-hev','sorento','sorento-hev','Tucson','avante','k5','k5-hev','new-grandeur','new-grandeur-hev','k8','k8-hev','xc40']));
check('Santa Fe initial no options',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:5},[]);assert.equal(x.trimId,'ex2wd');assert.equal(x.estimate.optionCost,0);assert.equal(x.estimate.base,4022);});
check('Santa Fe 360: 119万 option',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:5},['surround']);assert.equal(x.trimId,'ex2wd');assert.deepEqual([...x.optionIds],['parking']);assert.equal(x.estimate.optionCost,119);assert.equal(x.estimate.base,4022);});
check('Santa Fe 360+HUD: 178万',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:5},['surround','hud']);assert.equal(x.estimate.optionCost,178);assert.equal(x.estimate.vehiclePrice,4200);});
check('Santa Fe seven passengers: +69万',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:7},['surround']);assert.equal(x.seats,7);assert.equal(x.estimate.optionCost,188);assert(x.optionIds.includes('seat7'));});
check('Santa Fe six passengers uses feasible cheaper seven-seat option',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:6},['surround']);assert.equal(x.seats,7);assert(x.optionIds.includes('seat7'));});
check('Santa Fe H-Pick surround and HUD included',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:5},['surround','hud'],{trimId:'hp2wd'});assert.equal(x.estimate.optionCost,0);assert.equal(x.estimate.base,4573);});
check('Santa Fe Best Selection and parking mutually exclusive',()=>assert.equal(fit.optionClosure(verified.trim('santafe-hev','ex2wd').options,['best','parking']),null));
check('Santa Fe seat6 and seat7 are exclusive',()=>assert.equal(fit.optionClosure(verified.trim('santafe-hev','ex2wd').options,['seat6','seat7']),null));
check('Seltos base smart cruise is included',()=>{const x=fit.fitVerified(car('seltos'),{seats:5},['cruise']);assert.equal(x.trimId,'trendy');assert.equal(x.estimate.optionCost,0);});
check('Seltos monitoring package priced',()=>{const x=fit.fitVerified(car('seltos'),{seats:5},['surround']);assert(x.optionIds.includes('monitor'));assert.equal(x.estimate.optionCost,104);});
check('Seltos front seat ventilation and surround',()=>{const x=fit.fitVerified(car('seltos'),{seats:5},['vent','surround']);assert(x.features.includes('vent'));assert.equal(x.estimate.optionCost,104);});
check('Seltos no unsupported powered tailgate',()=>assert.equal(fit.fitVerified(car('seltos'),{seats:5},['trunk']).status,'unavailable'));
check('Carnival monitoring prerequisite priced once',()=>{const x=fit.fitVerified(car('carnival'),{seats:9},['surround']);assert(x.optionIds.includes('cluster'));assert.equal(x.estimate.optionCost,150);});
check('Palisade 9-seat base price + parking 113',()=>{const x=fit.fitVerified(car('palisade'),{seats:9},['surround']);assert.equal(x.trimId,'exclusive9');assert.equal(x.estimate.base,4478);assert.equal(x.estimate.optionCost,113);});
check('Unverified remainder not marked confirmed',()=>{const r=fit.recommend(vehicles,{seats:5,budget:7000,requiredFeatures:['surround']},core.rank);assert(r.confirmed.every(c=>verified.get(c.id)));assert(r.pending.every(c=>!verified.get(c.id)));});
check('Overbudget with required packages',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:7,budget:4100},['surround']);assert.equal(x.withinBudget,false);});
check('Paid manual option honored by fitted price',()=>{const x=fit.fitVerified(car('santafe-hev'),{seats:7},['surround'],{trimId:'ex2wd',lockedOptionIds:['roof']});assert.equal(x.estimate.optionCost,287);assert(x.optionIds.includes('roof'));});
check('Unverified feature does not silently cost zero',()=>assert.equal(fit.fitVerified(car('palisade'),{seats:9},['audio']).status,'unavailable'));
check('Sportage GAS Prestige official baseline',()=>{const x=fit.fitVerified(car('sportage'),{seats:5},['cruise','hda']);assert.equal(x.trimId,'gas-prestige');assert.equal(x.estimate.base,2944);});
check('Sportage GAS 360 selects Noblesse + Monitoring',()=>{const x=fit.fitVerified(car('sportage'),{seats:5},['surround']);assert.equal(x.trimId,'gas-noblesse');assert.equal(x.estimate.optionCost,114);assert.deepEqual([...x.optionIds],['monitor']);});
check('Sportage HEV 360 + HUD totals 173',()=>{const x=fit.fitVerified(car('sportage-hev'),{seats:5},['surround','hud']);assert.equal(x.trimId,'hev-noblesse');assert.equal(x.estimate.optionCost,173);assert.equal(x.estimate.vehiclePrice,3976);});
check('Sportage HEV 360 + HUD + AWD totals 396',()=>{const x=fit.fitVerified(car('sportage-hev'),{seats:5},['surround','hud','awd']);assert.equal(x.estimate.optionCost,396);});
check('Sportage HEV 360 + HUD on Signature HUD included',()=>{const x=fit.fitVerified(car('sportage-hev'),{seats:5},['surround','hud'],{trimId:'hev-signature'});assert.equal(x.estimate.optionCost,114);});
check('Sportage Prestige 360 correctly unavailable',()=>assert.equal(fit.fitVerified(car('sportage-hev'),{seats:5},['surround'],{trimId:'hev-prestige'}).status,'unavailable'));
check('Sorento GAS surround chooses Noblesse basic 0 paid',()=>{const x=fit.fitVerified(car('sorento'),{seats:5},['surround']);assert.equal(x.trimId,'gas-noblesse');assert.equal(x.estimate.base,3966);assert.equal(x.estimate.optionCost,0);});
check('Sorento HEV surround Noblesse base no option surcharge',()=>{const x=fit.fitVerified(car('sorento-hev'),{seats:5},['surround']);assert.equal(x.trimId,'hev-noblesse');assert.equal(x.estimate.base,4299);assert.equal(x.estimate.optionCost,0);});
check('Sorento HEV 7 people plus surround 69',()=>{const x=fit.fitVerified(car('sorento-hev'),{seats:7},['surround']);assert.equal(x.trimId,'hev-noblesse');assert.equal(x.estimate.optionCost,69);assert(x.optionIds.includes('seat7'));});
check('Sorento HEV Prestige HUD must include cluster',()=>{const x=fit.fitVerified(car('sorento-hev'),{seats:5},['hud'],{trimId:'hev-prestige'});assert.equal(x.estimate.optionCost,178);assert.deepEqual([...x.optionIds],['cluster','hud']);});
check('Sorento HEV Noblesse HUD no prerequisite',()=>{const x=fit.fitVerified(car('sorento-hev'),{seats:5},['hud'],{trimId:'hev-noblesse'});assert.equal(x.estimate.optionCost,119);});
check('Sorento HEV AWD not mislabeled confirmed for 2WD',()=>assert.equal(fit.fitVerified(car('sorento-hev'),{seats:5},['awd']).status,'unavailable'));
check('Sorento GAS AWD price 232',()=>{const x=fit.fitVerified(car('sorento'),{seats:5},['awd']);assert.equal(x.estimate.optionCost,232);});
check('Budget limit includes checked options',()=>{const x=fit.fitVerified(car('sportage-hev'),{seats:5,budget:3900},['surround','hud']);assert.equal(x.withinBudget,false);});
check('Verified 17 models supported by search',()=>{const r=fit.recommend(vehicles,{seats:5,budget:6000,requiredFeatures:['surround']},core.rank);assert.equal(Object.keys(verified.catalog).length,17);assert(r.confirmed.some(v=>v.id==='sportage-hev'));assert(r.confirmed.some(v=>v.id==='sorento-hev'));});

check('Tucson premium 360 is priced 123',()=>{const x=fit.fitVerified(car('Tucson'),{seats:5},['surround']);assert.equal(x.trimId,'gas-premium');assert.equal(x.estimate.base,3112);assert.equal(x.estimate.optionCost,123);});
check('Tucson Modern smart cruise adds 40',()=>{const x=fit.fitVerified(car('Tucson'),{seats:5},['cruise'],{trimId:'gas-modern'});assert.equal(x.estimate.base,2844);assert.equal(x.estimate.optionCost,40);assert(x.optionIds.includes('smart'));});
check('Tucson Modern HDA unverified',()=>assert.equal(fit.fitVerified(car('Tucson'),{seats:5},['hda'],{trimId:'gas-modern'}).status,'unavailable'));
check('Tucson premium cruise+360 totals 163 in options',()=>{const x=fit.fitVerified(car('Tucson'),{seats:5},['surround','cruise','hda']);assert.equal(x.trimId,'gas-premium');assert.equal(x.estimate.optionCost,163);});
check('Tucson comfort II conflicts with smart sense',()=>assert.equal(fit.optionClosure(verified.trim('Tucson','gas-premium').options,['smart','comfort2']),null));
check('Avante modern smart cruise is base',()=>{const x=fit.fitVerified(car('avante'),{seats:5},['cruise']);assert.equal(x.trimId,'gas-modern');assert.equal(x.estimate.base,2398);assert.equal(x.estimate.optionCost,0);});
check('Avante HDA starts premium 2771',()=>{const x=fit.fitVerified(car('avante'),{seats:5},['hda']);assert.equal(x.trimId,'gas-premium');assert.equal(x.estimate.base,2771);});
check('Avante premium sunroof adds 90',()=>{const x=fit.fitVerified(car('avante'),{seats:5},['hda','sunroof']);assert.equal(x.estimate.optionCost,90);});
check('Avante surround unavailable, not free',()=>assert.equal(fit.fitVerified(car('avante'),{seats:5},['surround']).status,'unavailable'));
check('K5 2.0 gas premium basic smart cruise',()=>{const x=fit.fitVerified(car('k5'),{seats:5},['cruise','hda']);assert.equal(x.estimate.base,2892);assert.equal(x.estimate.optionCost,0);});
check('K5 2.0 gas surround chooses Noblesse',()=>{const x=fit.fitVerified(car('k5'),{seats:5},['surround']);assert.equal(x.trimId,'gas-noblesse');assert.equal(x.estimate.optionCost,0);});
check('K5 gas powered trunk not conflated with Smart Trunk',()=>{const x=fit.fitVerified(car('k5'),{seats:5},['trunk']);assert.equal(x.trimId,'gas-noblesse');assert.equal(x.estimate.base,3244);});
check('K5 HEV base 3334, smart cruise included',()=>{const x=fit.fitVerified(car('k5-hev'),{seats:5},['cruise']);assert.equal(x.trimId,'hev-prestige');assert.equal(x.estimate.base,3334);});
check('K5 HEV 360 cheaper Best Selection+115',()=>{const x=fit.fitVerified(car('k5-hev'),{seats:5},['surround']);assert.equal(x.trimId,'hev-best');assert.equal(x.estimate.optionCost,115);});
check('K5 HEV 360+HUD chooses Noblesse+HUD',()=>{const x=fit.fitVerified(car('k5-hev'),{seats:5},['surround','hud']);assert.equal(x.trimId,'hev-noblesse');assert.equal(x.estimate.optionCost,109);});
check('K5 HEV surround verified price within budget check',()=>{const x=fit.fitVerified(car('k5-hev'),{seats:5,budget:3600},['surround']);assert.equal(x.withinBudget,false);});
check('Grandeur GAS parking package 170',()=>{const x=fit.fitVerified(car('new-grandeur'),{seats:5},['surround']);assert.equal(x.trimId,'gas-premium');assert.equal(x.estimate.optionCost,170);});
check('Grandeur GAS Exclusive surround base',()=>{const x=fit.fitVerified(car('new-grandeur'),{seats:5},['surround'],{trimId:'gas-exclusive'});assert.equal(x.estimate.optionCost,0);assert.equal(x.estimate.base,4694);});
check('Grandeur gasoline HTRAC unverified (no fake 2.5 AWD)',()=>assert.equal(fit.fitVerified(car('new-grandeur'),{seats:5},['awd']).status,'unavailable'));
check('Grandeur HEV Premium surround +170',()=>{const x=fit.fitVerified(car('new-grandeur-hev'),{seats:5},['surround']);assert.equal(x.estimate.base,4833);assert.equal(x.estimate.optionCost,170);});
check('Grandeur HEV Exclusive surround base 0',()=>{const x=fit.fitVerified(car('new-grandeur-hev'),{seats:5},['surround'],{trimId:'hev-exclusive'});assert.equal(x.estimate.optionCost,0);});
check('Grandeur HEV sunroof 120',()=>{const x=fit.fitVerified(car('new-grandeur-hev'),{seats:5},['sunroof']);assert.equal(x.estimate.optionCost,120);});
check('All new audits official URLs and fixed schema',()=>{for(const [id,audit] of Object.entries(verified.catalog)){assert(audit.url.startsWith('https://'));for(const trim of audit.trims){assert(trim.price>0);assert(trim.seats>=1);const seen=new Set();for(const o of trim.options){assert(o.price>=0);assert(!seen.has(o.id));seen.add(o.id);}}}});
check('Recommender confirmed only audit-registered cars',()=>{const x=fit.recommend(vehicles,{seats:5,budget:5500,requiredFeatures:['surround']},core.rank);assert(x.confirmed.some(v=>v.id==='new-grandeur'));assert(x.confirmed.some(v=>v.id==='Tucson'));assert(x.confirmed.every(v=>verified.get(v.id)));});

check('K8 gasoline base 3731',()=>{const x=fit.fitVerified(car('k8'),{seats:5},['cruise','hda']);assert.equal(x.trimId,'gas-25-light');assert.equal(x.estimate.base,3731);assert.equal(x.estimate.optionCost,0);});
check('K8 gasoline surround upgrades to Best Selection 4172',()=>{const x=fit.fitVerified(car('k8'),{seats:5},['surround']);assert.equal(x.trimId,'gas-25-best');assert.equal(x.estimate.base,4172);assert.equal(x.estimate.optionCost,0);});
check('K8 gasoline 360+panorama sunroof is 109',()=>{const x=fit.fitVerified(car('k8'),{seats:5},['surround','sunroof']);assert.equal(x.trimId,'gas-25-best');assert.equal(x.estimate.optionCost,109);});
check('K8 gasoline powered tailgate not base-only',()=>{const x=fit.fitVerified(car('k8'),{seats:5},['trunk']);assert.equal(x.trimId,'gas-25-best');});
check('K8 HEV 4267 starting price',()=>{const x=fit.fitVerified(car('k8-hev'),{seats:5},[]);assert.equal(x.trimId,'hev-light');assert.equal(x.estimate.base,4267);});
check('K8 HEV surround upgrades to Best Selection 4420',()=>{const x=fit.fitVerified(car('k8-hev'),{seats:5},['surround']);assert.equal(x.trimId,'hev-best');assert.equal(x.estimate.base,4420);assert.equal(x.estimate.optionCost,0);});
check('K8 HEV Meridian premium sound adds 109',()=>{const x=fit.fitVerified(car('k8-hev'),{seats:5},['surround','audio']);assert.equal(x.trimId,'hev-best');assert.equal(x.estimate.optionCost,109);});
check('K8 HEV base driver ventilation is not both front seats',()=>{const x=fit.fitVerified(car('k8-hev'),{seats:5},['vent']);assert.equal(x.trimId,'hev-best');});
check('K8 6-person impossible even if 5-seat vehicle looks spacious',()=>assert.equal(fit.fitVerified(car('k8'),{seats:6},[]).status,'unavailable'));
check('2027 Sonata prices refreshed from manufacturer announcement',()=>{assert.equal(car('sonata').price,2876);assert.equal(car('sonata-hev').price,3328);});
check('Sonata 2027 unverified options remain pending',()=>{assert.equal(verified.get('sonata'),null);assert.equal(verified.get('sonata-hev'),null);});
check('Avante HEV / Tucson HEV remain option unverified',()=>{assert.equal(verified.get('avante-hev'),null);assert.equal(verified.get('Tucson-hev'),null);});

console.log('ALL PASS '+n+' feature-fit checks');

// v2.7.0 imported Volvo B4 AWD genuine Korea manufacturer configuration.
const volvo=verified.get('xc40');if(!volvo||volvo.trims.length!==2)throw Error('Volvo package audit missing');console.log('PASS Volvo XC40 B4 AWD Plus and Ultra official trims');
